#!/usr/bin/env python

import argparse
import sys
import os

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/src")

from dataset import *
from supervisor import *

parser = argparse.ArgumentParser()

parser.add_argument('-c', '--create', action='store_true',
        help ="Create dataset")
parser.add_argument('-f', '--fill', action='store_true',
        help ="Fetch historical quotes")
parser.add_argument('-u', '--update', action='store_true',
        help ="Update dataset with newest quotes")

args = parser.parse_args()

if args.create:
    sys.exit('FATAL')

#=======================================================================================

DbSupervisor.establishMySqlConnection()

datasets = [
    US500('spy'),
    DAX30('dax'),
    FTSE100('ftse'),
    WIG20('wig')
]

print('Handled datasets:')
for ds in datasets:
    print(ds.getName())

if args.create:
    print("This is some output")
elif args.fill:
    print("This is some toutput")
elif args.update:
    print("This is some noutput")

#for ds in datasets:
    # print(ds.getName())
    # ds.use()
    # ds.create()
    # ds.fill()
    # ds.update()

